# Site settings
baseurl: ""
url: "https://shahaliyev.org"
github_username: shahaliyev

author: 
  en: Ismayil Shahaliyev
  az: İsmayıl Şahəliyev

title: 
  en: Ismayil Shahaliyev
  az: İsmayıl Şahəliyev

description:
  en: Computer Scientist | International Chess Master
  az: Kompüter Alimi | Beynəlxalq Şahmat Ustası

nav:
  home: 
    en: Home
    az: Ana səhifə
  writings: 
    en: Writings
    az: Yazılar


google_analytics: G-S1QRRQG9BM


collections:
  posts:
    output: true
    permalink: /writings/:title


defaults:
  -
    scope:
      path: ""
    values:
      lang: "en"
  -
    scope:
      path: "_posts"
    values:
      layout: "post"
  -
    scope:
      path: "_posts/az"
    values:
      lang: "az"
      permalink: "/az/writings/:title"
  -
    scope:
      path: "az"
    values:
      lang: "az"


# Build settings
theme:
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/